apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-npvinhphat-com-tls
spec:
  secretName: multi-k8s-npvinhphat-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - multi-k8s.npvinhphat.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.npvinhphat.com
